### ISSUE TITLE
Error running vignette

### ISSUE THREAD

**Issue by P-Rafter** [junyangq/snpnet#31] opened 2019-10-23 15:00 UTC
Hi Junyang,

I am trying to run the code given in vignette.Rmd for snpnet but I have run into the following error:

Error in if (file.exists(file.path) && !recompute) { :
  missing value where TRUE/FALSE needed
Calls: snpnet -> computeStats -> compute.summary.stats

If you have run into this error before could you let me know how to resolve it please?

Regards,
Pierce

**Comment by tdelhomme** [comment] 2020-03-11 15:39
Got the same error. Here is my config:

```
> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.2                         
year           2019                        
month          12                          
day            12                          
svn rev        77560                       
language       R                           
version.string R version 3.6.2 (2019-12-12)
nickname       Dark and Stormy Night  
```

**Comment by Keisarinn** [comment] 2020-04-27 10:10
I get the same error. I wonder what the problem is.

**Comment by junyangq** [comment] 2020-05-08 02:45
Sorry for the delay. It should have been fixed now.

**Closed as completed** 2022-03-14 01:25 UTC
